export * as ts from "./module";

export {
  getEmitModuleResolutionKind,
  getFileMatcherPatterns,
  injectTypeScriptModule,
  matchFiles,
  CompilerOptions,
  DiagnosticCategory,
  EmitHint,
  FileMatcherPatterns,
  FileSystemEntries,
  LanguageVariant,
  ModuleKind,
  ModuleResolutionKind,
  NewLineKind,
  NodeFlags,
  ObjectFlags,
  ScriptKind,
  ScriptSnapshot,
  ScriptTarget,
  SymbolFlags,
  SyntaxKind,
  TypeFlags,
  TypeFormatFlags,
} from "./module";
